//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Customer_CustomField = new HashSet<Customer_CustomField>();
            this.Customer_Documents = new HashSet<Customer_Documents>();
            this.Customers_Locations = new HashSet<Customers_Locations>();
            this.JobOrder_header = new HashSet<JobOrder_header>();
            this.Memberships = new HashSet<Membership>();
        }
    
        public int Customer_ID { get; set; }
        public string Customer_Ref_Code { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<System.Guid> AccountmanagerUserID { get; set; }
        public string Primary_Address { get; set; }
        public Nullable<int> Primary_City { get; set; }
        public string Primary_City_Name { get; set; }
        public string Primary_Add_Area { get; set; }
        public Nullable<int> Primary_State { get; set; }
        public Nullable<int> Primary_Country { get; set; }
        public string Primary_ZipCode { get; set; }
        public string Additional_Address_info { get; set; }
        public string Email_ID { get; set; }
        public string Primary_Phone { get; set; }
        public string Primary_Phone_Ext { get; set; }
        public Nullable<System.DateTime> Lease_Start_Date { get; set; }
        public Nullable<System.DateTime> Lease_end_date { get; set; }
        public string Acct_manager_Name { get; set; }
        public string Acct_manager_Primary_Address { get; set; }
        public string Acct_manager_Additional_Address_info { get; set; }
        public Nullable<int> Acct_manager_Primary_City { get; set; }
        public string Acct_manager_Primary_City_Name { get; set; }
        public string Acct_manager_Primary_Add_Area { get; set; }
        public Nullable<int> Acct_manager_Primary_State { get; set; }
        public Nullable<int> Acct_manager_Primary_Country { get; set; }
        public string Acct_manager_Primary_Zip { get; set; }
        public string Acct_manager_Primary_Phone { get; set; }
        public Nullable<int> Membership_Duration { get; set; }
        public Nullable<int> Membership_renew_duration { get; set; }
        public Nullable<int> NoofRevivesAllowed { get; set; }
        public Nullable<int> NoofRenewalRevivesAllowed { get; set; }
        public Nullable<int> EligibiltyWaitPeriod { get; set; }
        public bool Status { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<int> VoidDays { get; set; }
        public Nullable<System.Guid> APIKey { get; set; }
        public Nullable<bool> IsMultiDevice { get; set; }
        public Nullable<int> MaxNoOfDevices { get; set; }
        public Nullable<int> TemplateId { get; set; }
    
        public virtual ICollection<Customer_CustomField> Customer_CustomField { get; set; }
        public virtual ICollection<Customer_Documents> Customer_Documents { get; set; }
        public virtual ICollection<Customers_Locations> Customers_Locations { get; set; }
        public virtual ICollection<JobOrder_header> JobOrder_header { get; set; }
        public virtual ICollection<Membership> Memberships { get; set; }
    }
}
