//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Debug_Templates_Definition
    {
        public int Template_Definition_Id { get; set; }
        public int Template_ID { get; set; }
        public string VersionNumber { get; set; }
        public Nullable<int> DebugParameter_Id { get; set; }
        public string DebugParameter_default_value { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Debug_Templates Debug_Templates { get; set; }
    }
}
