//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupsPriority
    {
        public GroupsPriority()
        {
            this.LocationGroups = new HashSet<LocationGroup>();
        }
    
        public int PriorityId { get; set; }
        public string PriorityName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual ICollection<LocationGroup> LocationGroups { get; set; }
    }
}
