//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOrder_Machine_Mapping
    {
        public JobOrder_Machine_Mapping()
        {
            this.JobOrder_Machine_activity_detail = new HashSet<JobOrder_Machine_activity_detail>();
            this.JobOrder_Machine_TestResultsFinal = new HashSet<JobOrder_Machine_TestResultsFinal>();
            this.JobOrder_Machine_TestResultsMidLine = new HashSet<JobOrder_Machine_TestResultsMidLine>();
            this.JobOrder_Machine_TestResultsUL = new HashSet<JobOrder_Machine_TestResultsUL>();
            this.MachineReplacedHistories = new HashSet<MachineReplacedHistory>();
        }
    
        public int JobOrder_Machine_mapping_ID { get; set; }
        public Nullable<int> JobOrder_Header_ID { get; set; }
        public Nullable<int> JobOrder_Location_id { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> MidlineTesting_Stage_Id { get; set; }
        public Nullable<bool> MidlineTesting_Status { get; set; }
        public Nullable<int> ULLineTesting_Stage_Id { get; set; }
        public Nullable<bool> ULLineTesting_Status { get; set; }
        public Nullable<int> FinalTesting_Stage_Id { get; set; }
        public Nullable<bool> FinalTesting_Status { get; set; }
        public string Shipping_ID { get; set; }
        public int Machine_Status_Id { get; set; }
        public Nullable<int> Softwareversion_Id { get; set; }
        public Nullable<int> Proposedversion_id { get; set; }
        public string Special_instructions { get; set; }
        public string JobOrder_Logistics_DocPath { get; set; }
        public string JobOrder_Logistics_DocName { get; set; }
        public Nullable<System.DateTime> JobOrder_Logistics_Docuploadeddate { get; set; }
        public Nullable<System.Guid> JobOrder_Logistics_DocuploadedbyUserid { get; set; }
        public Nullable<System.Guid> JobOrder_Logistics_DocdownloadedbyUserid { get; set; }
        public Nullable<System.DateTime> JobOrder_Logistics_Docdownloadeddate { get; set; }
        public Nullable<System.Guid> Primary_Assigned_touserId { get; set; }
        public Nullable<bool> IsReplaced { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> IsMoved { get; set; }
        public string ShippingLabelData { get; set; }
    
        public virtual JobOrder_header JobOrder_header { get; set; }
        public virtual JobOrder_Locations JobOrder_Locations { get; set; }
        public virtual ICollection<JobOrder_Machine_activity_detail> JobOrder_Machine_activity_detail { get; set; }
        public virtual JobOrder_Machine_Id JobOrder_Machine_Id { get; set; }
        public virtual MasterData_Config_definitions MasterData_Config_definitions { get; set; }
        public virtual ICollection<JobOrder_Machine_TestResultsFinal> JobOrder_Machine_TestResultsFinal { get; set; }
        public virtual ICollection<JobOrder_Machine_TestResultsMidLine> JobOrder_Machine_TestResultsMidLine { get; set; }
        public virtual ICollection<JobOrder_Machine_TestResultsUL> JobOrder_Machine_TestResultsUL { get; set; }
        public virtual JobOrder_Status JobOrder_Status { get; set; }
        public virtual MasterData_Config_definitions MasterData_Config_definitions1 { get; set; }
        public virtual MasterData_Config_definitions MasterData_Config_definitions2 { get; set; }
        public virtual ICollection<MachineReplacedHistory> MachineReplacedHistories { get; set; }
        public virtual MasterData_Config_definitions MasterData_Config_definitions3 { get; set; }
    }
}
