//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOrder_header
    {
        public JobOrder_header()
        {
            this.JobOrder_Locations = new HashSet<JobOrder_Locations>();
            this.JobOrder_Machine_Mapping = new HashSet<JobOrder_Machine_Mapping>();
        }
    
        public int JobOrder_Header_ID { get; set; }
        public int Customer_ID { get; set; }
        public Nullable<int> Subsidiary_ID { get; set; }
        public Nullable<int> SubAgent_ID { get; set; }
        public int JobOrder_Status_Id { get; set; }
        public string CustomerPoNumber { get; set; }
        public Nullable<int> Noof_Machines { get; set; }
        public Nullable<System.DateTime> Expected_Delivery_Date { get; set; }
        public Nullable<int> MachineSpec_Id { get; set; }
        public string Client_Exec_Notes_Instructions { get; set; }
        public string Approver_notes { get; set; }
        public string Download_Software_URL { get; set; }
        public Nullable<bool> Archive_flag { get; set; }
        public Nullable<System.DateTime> Approved_rejected_Date { get; set; }
        public Nullable<System.Guid> Approved_Rejected_by_Userid { get; set; }
        public string ManufacturerComments { get; set; }
        public Nullable<int> Manufacturer_Id { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Subsidiary Subsidiary { get; set; }
        public virtual ICollection<JobOrder_Locations> JobOrder_Locations { get; set; }
        public virtual JobOrder_Status JobOrder_Status { get; set; }
        public virtual ICollection<JobOrder_Machine_Mapping> JobOrder_Machine_Mapping { get; set; }
        public virtual SubAgent SubAgent { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
