//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOrder_Status
    {
        public JobOrder_Status()
        {
            this.JobOrder_header = new HashSet<JobOrder_header>();
            this.JobOrder_Machine_Mapping = new HashSet<JobOrder_Machine_Mapping>();
        }
    
        public int JobOrder_Status_Id { get; set; }
        public string Status_Name { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual ICollection<JobOrder_header> JobOrder_header { get; set; }
        public virtual ICollection<JobOrder_Machine_Mapping> JobOrder_Machine_Mapping { get; set; }
    }
}
