//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOrder_Testing_Attributes
    {
        public int JobOrder_testing_Attribute_ID { get; set; }
        public int Testing_Stage { get; set; }
        public Nullable<int> Testing_Module { get; set; }
        public Nullable<int> testing_Section { get; set; }
        public Nullable<int> testing_Attribute { get; set; }
        public string Testing_Attribute_UOM { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
