//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOrder_Machine_TestResultsFinal
    {
        public int JobOrder_Machine_Testing_id { get; set; }
        public Nullable<int> JobOrder_Machine_mapping_ID { get; set; }
        public Nullable<bool> Final_Assembly { get; set; }
        public string Final_Process_Id { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual JobOrder_Machine_Mapping JobOrder_Machine_Mapping { get; set; }
    }
}
