//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOrder_Machine_Id
    {
        public JobOrder_Machine_Id()
        {
            this.MachineTemplateMappings = new HashSet<MachineTemplateMapping>();
            this.JobOrder_Machine_Mapping = new HashSet<JobOrder_Machine_Mapping>();
        }
    
        public int Machine_Id { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public string Machine_Id_Val { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<int> Mode_id { get; set; }
        public Nullable<int> Location_Id { get; set; }
        public Nullable<int> Mapped_Location_Id { get; set; }
        public Nullable<System.DateTime> Mapped_Location_Date { get; set; }
        public Nullable<bool> IsTested { get; set; }
    
        public virtual ICollection<MachineTemplateMapping> MachineTemplateMappings { get; set; }
        public virtual ICollection<JobOrder_Machine_Mapping> JobOrder_Machine_Mapping { get; set; }
    }
}
