//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOrder_Locations
    {
        public JobOrder_Locations()
        {
            this.JobOrder_Machine_Mapping = new HashSet<JobOrder_Machine_Mapping>();
        }
    
        public int JobOrder_Location_Id { get; set; }
        public int JobOrder_Id { get; set; }
        public Nullable<int> Location_id { get; set; }
        public Nullable<int> No_of_Machines { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual JobOrder_header JobOrder_header { get; set; }
        public virtual ICollection<JobOrder_Machine_Mapping> JobOrder_Machine_Mapping { get; set; }
        public virtual Customers_Locations Customers_Locations { get; set; }
    }
}
