//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationGroup
    {
        public LocationGroup()
        {
            this.Customers_Locations = new HashSet<Customers_Locations>();
            this.MapLocationByGroups = new HashSet<MapLocationByGroup>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> Priority_Id { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public Nullable<int> ShippingStatus { get; set; }
    
        public virtual ICollection<Customers_Locations> Customers_Locations { get; set; }
        public virtual GroupsPriority GroupsPriority { get; set; }
        public virtual ICollection<MapLocationByGroup> MapLocationByGroups { get; set; }
    }
}
