//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationMapMachine
    {
        public int MapId { get; set; }
        public int Machine_Id { get; set; }
        public int Location_id { get; set; }
        public Nullable<System.Guid> Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string TrackingNumber { get; set; }
        public string ShippingLabelData { get; set; }
    
        public virtual Customers_Locations Customers_Locations { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
