//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine_TestResults
    {
        public int Machine_Testing_id { get; set; }
        public int Machine_Id { get; set; }
        public Nullable<bool> Dielectric_test { get; set; }
        public Nullable<int> Dielectric_Voltage { get; set; }
        public Nullable<decimal> Dielectric_Current { get; set; }
        public Nullable<int> Dielectric_Time { get; set; }
        public Nullable<bool> Ground_Test { get; set; }
        public Nullable<decimal> Ground_Resistance { get; set; }
        public Nullable<bool> Platen_time { get; set; }
        public Nullable<int> Platen_seconds { get; set; }
        public Nullable<bool> Platen_sensor { get; set; }
        public Nullable<decimal> Platen_delta { get; set; }
        public Nullable<bool> Injection_time { get; set; }
        public Nullable<int> Injection_seconds { get; set; }
        public Nullable<bool> Injection_sensor { get; set; }
        public Nullable<decimal> Injection_delta { get; set; }
        public Nullable<bool> Vaccum_time { get; set; }
        public Nullable<int> Vaccum_seconds { get; set; }
        public Nullable<bool> Vaccum_sensor { get; set; }
        public Nullable<decimal> Vaccum_delta { get; set; }
        public Nullable<bool> USB_Internal_sensor { get; set; }
        public Nullable<decimal> USB_Internal_delta { get; set; }
        public Nullable<bool> USB_External_sensor { get; set; }
        public Nullable<decimal> USB_External_delta { get; set; }
        public Nullable<bool> Relative_Sensor { get; set; }
        public Nullable<decimal> Relative_Delta { get; set; }
        public Nullable<bool> Drying_Process { get; set; }
        public Nullable<int> Drying_Cycles { get; set; }
        public string Test1_Name { get; set; }
        public Nullable<bool> Test1_Verified { get; set; }
        public string Test2_Name { get; set; }
        public Nullable<bool> Test2_Verified { get; set; }
        public string Test3_Name { get; set; }
        public Nullable<bool> Test3_Verified { get; set; }
        public Nullable<bool> Final_Assembly { get; set; }
        public string Final_Process_Id { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
