//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineReplacedHistory
    {
        public int Id { get; set; }
        public Nullable<int> OldMachineId { get; set; }
        public Nullable<int> NewMachineId { get; set; }
        public Nullable<int> JobOrder_Machine_mapping_ID { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual JobOrder_Machine_Mapping JobOrder_Machine_Mapping { get; set; }
    }
}
