//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineHistory_Configuration
    {
        public int Id { get; set; }
        public Nullable<int> ConfigureTypeId { get; set; }
        public string ConfiguredValue { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    }
}
