//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine_activity_detail
    {
        public int Activity_Detail_ID { get; set; }
        public Nullable<int> Machine_Id { get; set; }
        public Nullable<System.DateTime> Activity_Date { get; set; }
        public Nullable<int> Activity_type_id { get; set; }
        public string Activity_result { get; set; }
        public string Comments { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
