//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineHistory
    {
        public MachineHistory()
        {
            this.Machine_Documents = new HashSet<Machine_Documents>();
        }
    
        public int MachineHistory_ID { get; set; }
        public Nullable<int> Machine_ID { get; set; }
        public Nullable<int> ReasonTypeId { get; set; }
        public string Notes { get; set; }
        public string Attachments_Path { get; set; }
        public Nullable<int> StatusTypeId { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> Subsidiary_Id { get; set; }
        public Nullable<int> SubAgent_Id { get; set; }
        public Nullable<int> Location_Id { get; set; }
        public Nullable<int> TransactoionTypeId { get; set; }
        public string ShippingLabelData { get; set; }
    
        public virtual ICollection<Machine_Documents> Machine_Documents { get; set; }
    }
}
