//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineSpec
    {
        public int MachineSpec_ID { get; set; }
        public string Generation { get; set; }
        public string Pump { get; set; }
        public string Debug_Parameter_default_value { get; set; }
        public string Customfield1 { get; set; }
        public string Customfield2 { get; set; }
        public string Customfield3 { get; set; }
        public string Customfield4 { get; set; }
        public string Customfield5 { get; set; }
        public string PCB_Version { get; set; }
        public string INjection_Heater { get; set; }
        public string PowerSupply_1 { get; set; }
        public string PowerSupply_2 { get; set; }
        public string Valve_1 { get; set; }
        public string Valve_2 { get; set; }
        public string Valve_3 { get; set; }
        public Nullable<int> Firmware_Version { get; set; }
        public string Platen_heater { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public System.DateTime Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
