//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapLocationByGroup
    {
        public int MapId { get; set; }
        public int GroupId { get; set; }
        public int Location_Id { get; set; }
        public int DeploymentStatusId { get; set; }
        public System.DateTime ShippingDate { get; set; }
        public Nullable<int> No_Of_Machines { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Customers_Locations Customers_Locations { get; set; }
        public virtual LocationGroup LocationGroup { get; set; }
    }
}
