//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterData_Config_definitions
    {
        public MasterData_Config_definitions()
        {
            this.MachinefaultParameterValues = new HashSet<MachinefaultParameterValue>();
            this.JobOrder_Machine_Mapping = new HashSet<JobOrder_Machine_Mapping>();
            this.JobOrder_Machine_Mapping1 = new HashSet<JobOrder_Machine_Mapping>();
            this.JobOrder_Machine_Mapping2 = new HashSet<JobOrder_Machine_Mapping>();
            this.JobOrder_Machine_Mapping3 = new HashSet<JobOrder_Machine_Mapping>();
            this.Machines = new HashSet<Machine>();
        }
    
        public int MasterData_Type_ID { get; set; }
        public string MasterData_Type { get; set; }
        public string MasterData_Value { get; set; }
        public string Custom_Field1 { get; set; }
        public string CustomField2 { get; set; }
        public string CustomField3 { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> status { get; set; }
        public string CustomField4 { get; set; }
    
        public virtual ICollection<MachinefaultParameterValue> MachinefaultParameterValues { get; set; }
        public virtual ICollection<JobOrder_Machine_Mapping> JobOrder_Machine_Mapping { get; set; }
        public virtual ICollection<JobOrder_Machine_Mapping> JobOrder_Machine_Mapping1 { get; set; }
        public virtual ICollection<JobOrder_Machine_Mapping> JobOrder_Machine_Mapping2 { get; set; }
        public virtual ICollection<JobOrder_Machine_Mapping> JobOrder_Machine_Mapping3 { get; set; }
        public virtual ICollection<Machine> Machines { get; set; }
    }
}
