//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership
    {
        public Membership()
        {
            this.Memebership_Details = new HashSet<Memebership_Details>();
            this.Tablet_App_MemberActivity_Details = new HashSet<Tablet_App_MemberActivity_Details>();
        }
    
        public int Id { get; set; }
        public string Membership_ID { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string MemberName { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string Email_ID { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public Nullable<bool> IsLegacy { get; set; }
        public Nullable<bool> IsVoid { get; set; }
        public Nullable<bool> IsMultiDevice { get; set; }
    
        public virtual ICollection<Memebership_Details> Memebership_Details { get; set; }
        public virtual ICollection<Tablet_App_MemberActivity_Details> Tablet_App_MemberActivity_Details { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
