//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memebership_Details
    {
        public int Membership_Det_ID { get; set; }
        public string Membership_Id { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<System.DateTime> Membership_Start_date { get; set; }
        public Nullable<System.DateTime> Membership_End_date { get; set; }
        public Nullable<int> No_of_Free_dries { get; set; }
        public string Store_ID { get; set; }
        public string Revive_Device_ID { get; set; }
        public Nullable<int> Machine_ID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Invoice_No { get; set; }
        public Nullable<int> EligibiltyWaitPeriod { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual Membership Membership { get; set; }
    }
}
