//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Filter_Type
    {
        public int Filter_Type_Id { get; set; }
        public int Report_Id { get; set; }
        public string Filter_Type { get; set; }
        public string Fitler_Text { get; set; }
        public string Filter_Data_Type { get; set; }
        public int Priority { get; set; }
    
        public virtual Report_Master Report_Master { get; set; }
    }
}
