//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ReviveDBEntities : DbContext
    {
        public ReviveDBEntities()
            : base("name=ReviveDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer_CustomField> Customer_CustomField { get; set; }
        public virtual DbSet<Customer_Documents> Customer_Documents { get; set; }
        public virtual DbSet<Debug_Templates> Debug_Templates { get; set; }
        public virtual DbSet<Debug_Templates_Definition> Debug_Templates_Definition { get; set; }
        public virtual DbSet<FAQ_Management> FAQ_Management { get; set; }
        public virtual DbSet<JobOrder_Locations> JobOrder_Locations { get; set; }
        public virtual DbSet<JobOrder_Machine_activity_detail> JobOrder_Machine_activity_detail { get; set; }
        public virtual DbSet<JobOrder_Machine_TestResultsFinal> JobOrder_Machine_TestResultsFinal { get; set; }
        public virtual DbSet<JobOrder_Machine_TestResultsMidLine> JobOrder_Machine_TestResultsMidLine { get; set; }
        public virtual DbSet<JobOrder_Machine_TestResultsUL> JobOrder_Machine_TestResultsUL { get; set; }
        public virtual DbSet<JobOrder_Status> JobOrder_Status { get; set; }
        public virtual DbSet<JobOrder_Testing_Attributes> JobOrder_Testing_Attributes { get; set; }
        public virtual DbSet<MachineReplacedHistory> MachineReplacedHistories { get; set; }
        public virtual DbSet<MachineSpec> MachineSpecs { get; set; }
        public virtual DbSet<MachineTemplateMapping> MachineTemplateMappings { get; set; }
        public virtual DbSet<MapMode_UserType> MapMode_UserType { get; set; }
        public virtual DbSet<Membership_Survey> Membership_Survey { get; set; }
        public virtual DbSet<Membership_Survey_Results> Membership_Survey_Results { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Mode> Modes { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Report_Filter_Type> Report_Filter_Type { get; set; }
        public virtual DbSet<Report_Master> Report_Master { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Store_users> Store_users { get; set; }
        public virtual DbSet<User_Level> User_Level { get; set; }
        public virtual DbSet<User_Level_Menu_Mapping> User_Level_Menu_Mapping { get; set; }
        public virtual DbSet<UserMap_Controller_Action> UserMap_Controller_Action { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<MachinefaultParameterValue> MachinefaultParameterValues { get; set; }
        public virtual DbSet<Modes_configuration> Modes_configuration { get; set; }
        public virtual DbSet<Subsidiary> Subsidiaries { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<JobOrder_header> JobOrder_header { get; set; }
        public virtual DbSet<JobOrder_Machine_Id> JobOrder_Machine_Id { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<TabletAppLogFile> TabletAppLogFiles { get; set; }
        public virtual DbSet<MasterData_Config_definitions> MasterData_Config_definitions { get; set; }
        public virtual DbSet<MachineHistory_Configuration> MachineHistory_Configuration { get; set; }
        public virtual DbSet<MachineMovedHistory> MachineMovedHistories { get; set; }
        public virtual DbSet<GroupsPriority> GroupsPriorities { get; set; }
        public virtual DbSet<JobOrder_Machine_Mapping> JobOrder_Machine_Mapping { get; set; }
        public virtual DbSet<Customers_Locations> Customers_Locations { get; set; }
        public virtual DbSet<ShippingConfiguration> ShippingConfigurations { get; set; }
        public virtual DbSet<Machine_activity_detail> Machine_activity_detail { get; set; }
        public virtual DbSet<SubAgent> SubAgents { get; set; }
        public virtual DbSet<MachineOrder> MachineOrders { get; set; }
        public virtual DbSet<Machine_TestResults> Machine_TestResults { get; set; }
        public virtual DbSet<MapLocationByGroup> MapLocationByGroups { get; set; }
        public virtual DbSet<LocationGroup> LocationGroups { get; set; }
        public virtual DbSet<UPSSetting> UPSSettings { get; set; }
        public virtual DbSet<MachineHistory> MachineHistories { get; set; }
        public virtual DbSet<Tablet_App_Machine_Activity_Details> Tablet_App_Machine_Activity_Details { get; set; }
        public virtual DbSet<Machine> Machines { get; set; }
        public virtual DbSet<LocationMapMachine> LocationMapMachines { get; set; }
        public virtual DbSet<Tablet_App_NonMemberActivity_Details> Tablet_App_NonMemberActivity_Details { get; set; }
        public virtual DbSet<Tablet_App_Machine_Activity_Results> Tablet_App_Machine_Activity_Results { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
        public virtual DbSet<Memebership_Details> Memebership_Details { get; set; }
        public virtual DbSet<Tablet_App_MemberActivity_Details> Tablet_App_MemberActivity_Details { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Machine_Documents> Machine_Documents { get; set; }
    
        public virtual ObjectResult<usp_GetControllerActionByUserLevelID_Result> usp_GetControllerActionByUserLevelID(Nullable<int> user_level_id)
        {
            var user_level_idParameter = user_level_id.HasValue ?
                new ObjectParameter("user_level_id", user_level_id) :
                new ObjectParameter("user_level_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetControllerActionByUserLevelID_Result>("usp_GetControllerActionByUserLevelID", user_level_idParameter);
        }
    
        public virtual ObjectResult<usp_GetParameterNotMappedByTemplateID_Result> usp_GetParameterNotMappedByTemplateID(Nullable<int> templateId)
        {
            var templateIdParameter = templateId.HasValue ?
                new ObjectParameter("templateId", templateId) :
                new ObjectParameter("templateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetParameterNotMappedByTemplateID_Result>("usp_GetParameterNotMappedByTemplateID", templateIdParameter);
        }
    
        public virtual ObjectResult<usp_GetNotification_Result> usp_GetNotification(string loginMail_id)
        {
            var loginMail_idParameter = loginMail_id != null ?
                new ObjectParameter("loginMail_id", loginMail_id) :
                new ObjectParameter("loginMail_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetNotification_Result>("usp_GetNotification", loginMail_idParameter);
        }
    
        public virtual ObjectResult<usp_GetRoleDetails_Result> usp_GetRoleDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetRoleDetails_Result>("usp_GetRoleDetails");
        }
    
        public virtual ObjectResult<usp_GetOrders_MFShip_Result> usp_GetOrders_MFShip(string machineStatus, string orderStatus)
        {
            var machineStatusParameter = machineStatus != null ?
                new ObjectParameter("MachineStatus", machineStatus) :
                new ObjectParameter("MachineStatus", typeof(string));
    
            var orderStatusParameter = orderStatus != null ?
                new ObjectParameter("OrderStatus", orderStatus) :
                new ObjectParameter("OrderStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetOrders_MFShip_Result>("usp_GetOrders_MFShip", machineStatusParameter, orderStatusParameter);
        }
    
        public virtual ObjectResult<usp_GetMachineDetailByMachMapId_Result> usp_GetMachineDetailByMachMapId(Nullable<int> machMapId)
        {
            var machMapIdParameter = machMapId.HasValue ?
                new ObjectParameter("MachMapId", machMapId) :
                new ObjectParameter("MachMapId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMachineDetailByMachMapId_Result>("usp_GetMachineDetailByMachMapId", machMapIdParameter);
        }
    
        public virtual ObjectResult<usp_UpdateMembershipRenew_Result> usp_UpdateMembershipRenew(string memberShipId, Nullable<System.Guid> userId, string invoice_No)
        {
            var memberShipIdParameter = memberShipId != null ?
                new ObjectParameter("MemberShipId", memberShipId) :
                new ObjectParameter("MemberShipId", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var invoice_NoParameter = invoice_No != null ?
                new ObjectParameter("invoice_No", invoice_No) :
                new ObjectParameter("invoice_No", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_UpdateMembershipRenew_Result>("usp_UpdateMembershipRenew", memberShipIdParameter, userIdParameter, invoice_NoParameter);
        }
    
        public virtual ObjectResult<usp_GetModeValidate_Result> usp_GetModeValidate(Nullable<int> modeId, Nullable<int> machineId)
        {
            var modeIdParameter = modeId.HasValue ?
                new ObjectParameter("ModeId", modeId) :
                new ObjectParameter("ModeId", typeof(int));
    
            var machineIdParameter = machineId.HasValue ?
                new ObjectParameter("MachineId", machineId) :
                new ObjectParameter("MachineId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetModeValidate_Result>("usp_GetModeValidate", modeIdParameter, machineIdParameter);
        }
    
        public virtual ObjectResult<usp_GetShippedMachIds_Result> usp_GetShippedMachIds(Nullable<int> customer_id, Nullable<int> location_id)
        {
            var customer_idParameter = customer_id.HasValue ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(int));
    
            var location_idParameter = location_id.HasValue ?
                new ObjectParameter("location_id", location_id) :
                new ObjectParameter("location_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetShippedMachIds_Result>("usp_GetShippedMachIds", customer_idParameter, location_idParameter);
        }
    
        public virtual ObjectResult<usp_GetMappedMachinesByOrderId_Result> usp_GetMappedMachinesByOrderId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMappedMachinesByOrderId_Result>("usp_GetMappedMachinesByOrderId", idParameter);
        }
    
        public virtual ObjectResult<usp_GetOrderLocations_Result> usp_GetOrderLocations(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetOrderLocations_Result>("usp_GetOrderLocations", idParameter);
        }
    
        public virtual ObjectResult<usp_DeleteMembershipById_Result> usp_DeleteMembershipById(string memberShipId)
        {
            var memberShipIdParameter = memberShipId != null ?
                new ObjectParameter("MemberShipId", memberShipId) :
                new ObjectParameter("MemberShipId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_DeleteMembershipById_Result>("usp_DeleteMembershipById", memberShipIdParameter);
        }
    
        public virtual ObjectResult<usp_GetValidMemberById_Result> usp_GetValidMemberById(string email_Id)
        {
            var email_IdParameter = email_Id != null ?
                new ObjectParameter("Email_Id", email_Id) :
                new ObjectParameter("Email_Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetValidMemberById_Result>("usp_GetValidMemberById", email_IdParameter);
        }
    
        public virtual ObjectResult<usp_GetMyTaskByUserRole_Result> usp_GetMyTaskByUserRole(Nullable<System.Guid> acctmanagerUserId, Nullable<int> user_level_id, string statusCode, Nullable<int> manufacturerId)
        {
            var acctmanagerUserIdParameter = acctmanagerUserId.HasValue ?
                new ObjectParameter("acctmanagerUserId", acctmanagerUserId) :
                new ObjectParameter("acctmanagerUserId", typeof(System.Guid));
    
            var user_level_idParameter = user_level_id.HasValue ?
                new ObjectParameter("user_level_id", user_level_id) :
                new ObjectParameter("user_level_id", typeof(int));
    
            var statusCodeParameter = statusCode != null ?
                new ObjectParameter("statusCode", statusCode) :
                new ObjectParameter("statusCode", typeof(string));
    
            var manufacturerIdParameter = manufacturerId.HasValue ?
                new ObjectParameter("manufacturerId", manufacturerId) :
                new ObjectParameter("manufacturerId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMyTaskByUserRole_Result>("usp_GetMyTaskByUserRole", acctmanagerUserIdParameter, user_level_idParameter, statusCodeParameter, manufacturerIdParameter);
        }
    
        public virtual ObjectResult<usp_GetReviveDetails_Result> usp_GetReviveDetails(string processId, Nullable<int> machineId)
        {
            var processIdParameter = processId != null ?
                new ObjectParameter("ProcessId", processId) :
                new ObjectParameter("ProcessId", typeof(string));
    
            var machineIdParameter = machineId.HasValue ?
                new ObjectParameter("MachineId", machineId) :
                new ObjectParameter("MachineId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetReviveDetails_Result>("usp_GetReviveDetails", processIdParameter, machineIdParameter);
        }
    
        public virtual ObjectResult<usp_GetMachineIdByLocation_Result> usp_GetMachineIdByLocation(Nullable<int> customerId, Nullable<int> locationId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMachineIdByLocation_Result>("usp_GetMachineIdByLocation", customerIdParameter, locationIdParameter);
        }
    
        public virtual int usp_GetReconciliation(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo, Nullable<int> customerId, Nullable<int> subsidiaryId, Nullable<int> subAgentId, Nullable<int> locationId, Nullable<System.Guid> loginUserId, string pageAccessCode, Nullable<int> modeId)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("DateFrom", dateFrom) :
                new ObjectParameter("DateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("DateTo", dateTo) :
                new ObjectParameter("DateTo", typeof(System.DateTime));
    
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var subsidiaryIdParameter = subsidiaryId.HasValue ?
                new ObjectParameter("SubsidiaryId", subsidiaryId) :
                new ObjectParameter("SubsidiaryId", typeof(int));
    
            var subAgentIdParameter = subAgentId.HasValue ?
                new ObjectParameter("SubAgentId", subAgentId) :
                new ObjectParameter("SubAgentId", typeof(int));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(int));
    
            var loginUserIdParameter = loginUserId.HasValue ?
                new ObjectParameter("LoginUserId", loginUserId) :
                new ObjectParameter("LoginUserId", typeof(System.Guid));
    
            var pageAccessCodeParameter = pageAccessCode != null ?
                new ObjectParameter("PageAccessCode", pageAccessCode) :
                new ObjectParameter("PageAccessCode", typeof(string));
    
            var modeIdParameter = modeId.HasValue ?
                new ObjectParameter("ModeId", modeId) :
                new ObjectParameter("ModeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetReconciliation", dateFromParameter, dateToParameter, customerIdParameter, subsidiaryIdParameter, subAgentIdParameter, locationIdParameter, loginUserIdParameter, pageAccessCodeParameter, modeIdParameter);
        }
    
        public virtual ObjectResult<usp_Scheduler_GetCheckOutProcFailedDetails_Result> usp_Scheduler_GetCheckOutProcFailedDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Scheduler_GetCheckOutProcFailedDetails_Result>("usp_Scheduler_GetCheckOutProcFailedDetails");
        }
    
        public virtual ObjectResult<usp_Scheduler_GetCustomersLeaseEndingDetails_Result> usp_Scheduler_GetCustomersLeaseEndingDetails(Nullable<int> leaseDays)
        {
            var leaseDaysParameter = leaseDays.HasValue ?
                new ObjectParameter("LeaseDays", leaseDays) :
                new ObjectParameter("LeaseDays", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Scheduler_GetCustomersLeaseEndingDetails_Result>("usp_Scheduler_GetCustomersLeaseEndingDetails", leaseDaysParameter);
        }
    
        public virtual ObjectResult<usp_Scheduler_GetMachinesFailedDefaultParam_Result> usp_Scheduler_GetMachinesFailedDefaultParam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Scheduler_GetMachinesFailedDefaultParam_Result>("usp_Scheduler_GetMachinesFailedDefaultParam");
        }
    
        public virtual ObjectResult<usp_Scheduler_GetMachinesFailedToStart_Result> usp_Scheduler_GetMachinesFailedToStart()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Scheduler_GetMachinesFailedToStart_Result>("usp_Scheduler_GetMachinesFailedToStart");
        }
    
        public virtual ObjectResult<usp_GetOrders_Result> usp_GetOrders()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetOrders_Result>("usp_GetOrders");
        }
    
        public virtual ObjectResult<usp_GetReports_Result> usp_GetReports(Nullable<int> report_id, string param, Nullable<System.Guid> loginUserId, string pageAccessCode)
        {
            var report_idParameter = report_id.HasValue ?
                new ObjectParameter("Report_id", report_id) :
                new ObjectParameter("Report_id", typeof(int));
    
            var paramParameter = param != null ?
                new ObjectParameter("Param", param) :
                new ObjectParameter("Param", typeof(string));
    
            var loginUserIdParameter = loginUserId.HasValue ?
                new ObjectParameter("LoginUserId", loginUserId) :
                new ObjectParameter("LoginUserId", typeof(System.Guid));
    
            var pageAccessCodeParameter = pageAccessCode != null ?
                new ObjectParameter("PageAccessCode", pageAccessCode) :
                new ObjectParameter("PageAccessCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetReports_Result>("usp_GetReports", report_idParameter, paramParameter, loginUserIdParameter, pageAccessCodeParameter);
        }
    
        public virtual ObjectResult<usp_GetMachineIdCounterVal_Result> usp_GetMachineIdCounterVal(Nullable<System.DateTime> forDate, Nullable<int> valueType)
        {
            var forDateParameter = forDate.HasValue ?
                new ObjectParameter("ForDate", forDate) :
                new ObjectParameter("ForDate", typeof(System.DateTime));
    
            var valueTypeParameter = valueType.HasValue ?
                new ObjectParameter("valueType", valueType) :
                new ObjectParameter("valueType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMachineIdCounterVal_Result>("usp_GetMachineIdCounterVal", forDateParameter, valueTypeParameter);
        }
    
        public virtual ObjectResult<usp_GetMachineMapByCustomer_Result> usp_GetMachineMapByCustomer(Nullable<int> customerId, Nullable<int> locationId, Nullable<int> subsidiaryId, Nullable<int> agentId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("customerId", customerId) :
                new ObjectParameter("customerId", typeof(int));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("locationId", locationId) :
                new ObjectParameter("locationId", typeof(int));
    
            var subsidiaryIdParameter = subsidiaryId.HasValue ?
                new ObjectParameter("subsidiaryId", subsidiaryId) :
                new ObjectParameter("subsidiaryId", typeof(int));
    
            var agentIdParameter = agentId.HasValue ?
                new ObjectParameter("agentId", agentId) :
                new ObjectParameter("agentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMachineMapByCustomer_Result>("usp_GetMachineMapByCustomer", customerIdParameter, locationIdParameter, subsidiaryIdParameter, agentIdParameter);
        }
    
        public virtual ObjectResult<usp_GetMachineTemplate_Result> usp_GetMachineTemplate(Nullable<int> customer_Id, Nullable<int> location_Id, Nullable<int> subsidiary_Id, Nullable<int> subAgent_Id)
        {
            var customer_IdParameter = customer_Id.HasValue ?
                new ObjectParameter("customer_Id", customer_Id) :
                new ObjectParameter("customer_Id", typeof(int));
    
            var location_IdParameter = location_Id.HasValue ?
                new ObjectParameter("Location_Id", location_Id) :
                new ObjectParameter("Location_Id", typeof(int));
    
            var subsidiary_IdParameter = subsidiary_Id.HasValue ?
                new ObjectParameter("subsidiary_Id", subsidiary_Id) :
                new ObjectParameter("subsidiary_Id", typeof(int));
    
            var subAgent_IdParameter = subAgent_Id.HasValue ?
                new ObjectParameter("subAgent_Id", subAgent_Id) :
                new ObjectParameter("subAgent_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMachineTemplate_Result>("usp_GetMachineTemplate", customer_IdParameter, location_IdParameter, subsidiary_IdParameter, subAgent_IdParameter);
        }
    
        public virtual ObjectResult<usp_GetKillMachineByLocationAndCustomer_Result> usp_GetKillMachineByLocationAndCustomer(Nullable<int> customerId, Nullable<int> locationId, Nullable<int> subsidiaryId, Nullable<int> subAgentId)
        {
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(int));
    
            var subsidiaryIdParameter = subsidiaryId.HasValue ?
                new ObjectParameter("SubsidiaryId", subsidiaryId) :
                new ObjectParameter("SubsidiaryId", typeof(int));
    
            var subAgentIdParameter = subAgentId.HasValue ?
                new ObjectParameter("SubAgentId", subAgentId) :
                new ObjectParameter("SubAgentId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetKillMachineByLocationAndCustomer_Result>("usp_GetKillMachineByLocationAndCustomer", customerIdParameter, locationIdParameter, subsidiaryIdParameter, subAgentIdParameter);
        }
    
        public virtual ObjectResult<usp_GetMachineIdLocsListByOrderId_Result> usp_GetMachineIdLocsListByOrderId(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMachineIdLocsListByOrderId_Result>("usp_GetMachineIdLocsListByOrderId", idParameter);
        }
    
        public virtual ObjectResult<usp_GetMembershipDetails_Result> usp_GetMembershipDetails(string membershipId, string memberName, string emailId, string phoneNumber, Nullable<int> customerId, string invoice_no, Nullable<int> from_number, Nullable<int> to_number)
        {
            var membershipIdParameter = membershipId != null ?
                new ObjectParameter("MembershipId", membershipId) :
                new ObjectParameter("MembershipId", typeof(string));
    
            var memberNameParameter = memberName != null ?
                new ObjectParameter("MemberName", memberName) :
                new ObjectParameter("MemberName", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var invoice_noParameter = invoice_no != null ?
                new ObjectParameter("Invoice_no", invoice_no) :
                new ObjectParameter("Invoice_no", typeof(string));
    
            var from_numberParameter = from_number.HasValue ?
                new ObjectParameter("from_number", from_number) :
                new ObjectParameter("from_number", typeof(int));
    
            var to_numberParameter = to_number.HasValue ?
                new ObjectParameter("to_number", to_number) :
                new ObjectParameter("to_number", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMembershipDetails_Result>("usp_GetMembershipDetails", membershipIdParameter, memberNameParameter, emailIdParameter, phoneNumberParameter, customerIdParameter, invoice_noParameter, from_numberParameter, to_numberParameter);
        }
    
        public virtual ObjectResult<usp_GetOrderByID_Result> usp_GetOrderByID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetOrderByID_Result>("usp_GetOrderByID", idParameter);
        }
    
        public virtual ObjectResult<usp_GetUnassignedMachineToDelete_Result> usp_GetUnassignedMachineToDelete()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetUnassignedMachineToDelete_Result>("usp_GetUnassignedMachineToDelete");
        }
    
        public virtual ObjectResult<usp_UpdateMemberAsVoid_Result> usp_UpdateMemberAsVoid(string memberShipId, Nullable<System.Guid> userId)
        {
            var memberShipIdParameter = memberShipId != null ?
                new ObjectParameter("MemberShipId", memberShipId) :
                new ObjectParameter("MemberShipId", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_UpdateMemberAsVoid_Result>("usp_UpdateMemberAsVoid", memberShipIdParameter, userIdParameter);
        }
    
        public virtual ObjectResult<usp_GetReviveData_Result> usp_GetReviveData(string phoneNumber)
        {
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetReviveData_Result>("usp_GetReviveData", phoneNumberParameter);
        }
    
        public virtual ObjectResult<usp_GetAllModesByModeId_Result> usp_GetAllModesByModeId(Nullable<int> mode_Id, Nullable<int> customerID, Nullable<int> subsidiaryID, Nullable<int> subagentID, Nullable<int> locationID)
        {
            var mode_IdParameter = mode_Id.HasValue ?
                new ObjectParameter("mode_Id", mode_Id) :
                new ObjectParameter("mode_Id", typeof(int));
    
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("customerID", customerID) :
                new ObjectParameter("customerID", typeof(int));
    
            var subsidiaryIDParameter = subsidiaryID.HasValue ?
                new ObjectParameter("subsidiaryID", subsidiaryID) :
                new ObjectParameter("subsidiaryID", typeof(int));
    
            var subagentIDParameter = subagentID.HasValue ?
                new ObjectParameter("SubagentID", subagentID) :
                new ObjectParameter("SubagentID", typeof(int));
    
            var locationIDParameter = locationID.HasValue ?
                new ObjectParameter("LocationID", locationID) :
                new ObjectParameter("LocationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAllModesByModeId_Result>("usp_GetAllModesByModeId", mode_IdParameter, customerIDParameter, subsidiaryIDParameter, subagentIDParameter, locationIDParameter);
        }
    
        public virtual ObjectResult<usp_GetMachineHistory_Result> usp_GetMachineHistory(Nullable<int> customer_Id, Nullable<int> subsidiary_Id, Nullable<int> subAgentId, Nullable<int> locationId)
        {
            var customer_IdParameter = customer_Id.HasValue ?
                new ObjectParameter("customer_Id", customer_Id) :
                new ObjectParameter("customer_Id", typeof(int));
    
            var subsidiary_IdParameter = subsidiary_Id.HasValue ?
                new ObjectParameter("subsidiary_Id", subsidiary_Id) :
                new ObjectParameter("subsidiary_Id", typeof(int));
    
            var subAgentIdParameter = subAgentId.HasValue ?
                new ObjectParameter("SubAgentId", subAgentId) :
                new ObjectParameter("SubAgentId", typeof(int));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMachineHistory_Result>("usp_GetMachineHistory", customer_IdParameter, subsidiary_IdParameter, subAgentIdParameter, locationIdParameter);
        }
    
        public virtual ObjectResult<usp_GetMachineHistoryCustomerDetailsByMachineId_Result> usp_GetMachineHistoryCustomerDetailsByMachineId(Nullable<int> machineId)
        {
            var machineIdParameter = machineId.HasValue ?
                new ObjectParameter("machineId", machineId) :
                new ObjectParameter("machineId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMachineHistoryCustomerDetailsByMachineId_Result>("usp_GetMachineHistoryCustomerDetailsByMachineId", machineIdParameter);
        }
    
        public virtual ObjectResult<usp_GetMachineHistoryByMachineId_Result> usp_GetMachineHistoryByMachineId(Nullable<int> machineId)
        {
            var machineIdParameter = machineId.HasValue ?
                new ObjectParameter("machineId", machineId) :
                new ObjectParameter("machineId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMachineHistoryByMachineId_Result>("usp_GetMachineHistoryByMachineId", machineIdParameter);
        }
    
        public virtual ObjectResult<usp_GetGroupedLocationForShipByGroupId_Result> usp_GetGroupedLocationForShipByGroupId(Nullable<int> groupId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetGroupedLocationForShipByGroupId_Result>("usp_GetGroupedLocationForShipByGroupId", groupIdParameter);
        }
    
        public virtual ObjectResult<usp_GetShippedDetails_Result> usp_GetShippedDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetShippedDetails_Result>("usp_GetShippedDetails");
        }
    
        public virtual ObjectResult<usp_GetShippableDetailsByCustomerGroups_Result> usp_GetShippableDetailsByCustomerGroups()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetShippableDetailsByCustomerGroups_Result>("usp_GetShippableDetailsByCustomerGroups");
        }
    
        public virtual ObjectResult<usp_GetShippedMachinesByGroupId_Result> usp_GetShippedMachinesByGroupId(Nullable<int> groupId)
        {
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("groupId", groupId) :
                new ObjectParameter("groupId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetShippedMachinesByGroupId_Result>("usp_GetShippedMachinesByGroupId", groupIdParameter);
        }
    
        public virtual ObjectResult<usp_RegisterMembership_Result> usp_RegisterMembership(string memberName, string email_ID, string phone_Number, Nullable<System.DateTime> dob, Nullable<System.Guid> userId, string reviveDeviceId, Nullable<int> machineId, string invoice_No, Nullable<bool> isMultiDevice)
        {
            var memberNameParameter = memberName != null ?
                new ObjectParameter("MemberName", memberName) :
                new ObjectParameter("MemberName", typeof(string));
    
            var email_IDParameter = email_ID != null ?
                new ObjectParameter("Email_ID", email_ID) :
                new ObjectParameter("Email_ID", typeof(string));
    
            var phone_NumberParameter = phone_Number != null ?
                new ObjectParameter("Phone_Number", phone_Number) :
                new ObjectParameter("Phone_Number", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var reviveDeviceIdParameter = reviveDeviceId != null ?
                new ObjectParameter("reviveDeviceId", reviveDeviceId) :
                new ObjectParameter("reviveDeviceId", typeof(string));
    
            var machineIdParameter = machineId.HasValue ?
                new ObjectParameter("machineId", machineId) :
                new ObjectParameter("machineId", typeof(int));
    
            var invoice_NoParameter = invoice_No != null ?
                new ObjectParameter("invoice_No", invoice_No) :
                new ObjectParameter("invoice_No", typeof(string));
    
            var isMultiDeviceParameter = isMultiDevice.HasValue ?
                new ObjectParameter("IsMultiDevice", isMultiDevice) :
                new ObjectParameter("IsMultiDevice", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_RegisterMembership_Result>("usp_RegisterMembership", memberNameParameter, email_IDParameter, phone_NumberParameter, dobParameter, userIdParameter, reviveDeviceIdParameter, machineIdParameter, invoice_NoParameter, isMultiDeviceParameter);
        }
    
        public virtual ObjectResult<usp_vzMachineActivity_Result> usp_vzMachineActivity(string dateFromstr, string dateTostr, Nullable<int> customerId, Nullable<int> subsidiaryId, Nullable<int> subAgentId, Nullable<int> locationId, Nullable<int> modeId)
        {
            var dateFromstrParameter = dateFromstr != null ?
                new ObjectParameter("DateFromstr", dateFromstr) :
                new ObjectParameter("DateFromstr", typeof(string));
    
            var dateTostrParameter = dateTostr != null ?
                new ObjectParameter("DateTostr", dateTostr) :
                new ObjectParameter("DateTostr", typeof(string));
    
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var subsidiaryIdParameter = subsidiaryId.HasValue ?
                new ObjectParameter("SubsidiaryId", subsidiaryId) :
                new ObjectParameter("SubsidiaryId", typeof(int));
    
            var subAgentIdParameter = subAgentId.HasValue ?
                new ObjectParameter("SubAgentId", subAgentId) :
                new ObjectParameter("SubAgentId", typeof(int));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(int));
    
            var modeIdParameter = modeId.HasValue ?
                new ObjectParameter("ModeId", modeId) :
                new ObjectParameter("ModeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_vzMachineActivity_Result>("usp_vzMachineActivity", dateFromstrParameter, dateTostrParameter, customerIdParameter, subsidiaryIdParameter, subAgentIdParameter, locationIdParameter, modeIdParameter);
        }
    
        public virtual ObjectResult<usp_GetUserDetails_Result> usp_GetUserDetails(Nullable<int> user_Level_Id, Nullable<int> customer_Id, string userType, Nullable<int> subsidiary_Id, Nullable<int> subAgent_Id, Nullable<int> location_Id)
        {
            var user_Level_IdParameter = user_Level_Id.HasValue ?
                new ObjectParameter("User_Level_Id", user_Level_Id) :
                new ObjectParameter("User_Level_Id", typeof(int));
    
            var customer_IdParameter = customer_Id.HasValue ?
                new ObjectParameter("Customer_Id", customer_Id) :
                new ObjectParameter("Customer_Id", typeof(int));
    
            var userTypeParameter = userType != null ?
                new ObjectParameter("UserType", userType) :
                new ObjectParameter("UserType", typeof(string));
    
            var subsidiary_IdParameter = subsidiary_Id.HasValue ?
                new ObjectParameter("Subsidiary_Id", subsidiary_Id) :
                new ObjectParameter("Subsidiary_Id", typeof(int));
    
            var subAgent_IdParameter = subAgent_Id.HasValue ?
                new ObjectParameter("SubAgent_Id", subAgent_Id) :
                new ObjectParameter("SubAgent_Id", typeof(int));
    
            var location_IdParameter = location_Id.HasValue ?
                new ObjectParameter("Location_Id", location_Id) :
                new ObjectParameter("Location_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetUserDetails_Result>("usp_GetUserDetails", user_Level_IdParameter, customer_IdParameter, userTypeParameter, subsidiary_IdParameter, subAgent_IdParameter, location_IdParameter);
        }
    
        public virtual ObjectResult<usp_LegacyMemberInsert_Result> usp_LegacyMemberInsert(string memberName, string email_ID, string phone_Number, Nullable<System.Guid> userId, string reviveDeviceId, Nullable<int> machineId, string invoice_No, Nullable<bool> isLegacy, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> no_of_FreeDries, Nullable<int> customerId, Nullable<int> subdiaryId, Nullable<int> subAgentId, Nullable<int> locationId, Nullable<bool> isMultiDevice)
        {
            var memberNameParameter = memberName != null ?
                new ObjectParameter("MemberName", memberName) :
                new ObjectParameter("MemberName", typeof(string));
    
            var email_IDParameter = email_ID != null ?
                new ObjectParameter("Email_ID", email_ID) :
                new ObjectParameter("Email_ID", typeof(string));
    
            var phone_NumberParameter = phone_Number != null ?
                new ObjectParameter("Phone_Number", phone_Number) :
                new ObjectParameter("Phone_Number", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(System.Guid));
    
            var reviveDeviceIdParameter = reviveDeviceId != null ?
                new ObjectParameter("reviveDeviceId", reviveDeviceId) :
                new ObjectParameter("reviveDeviceId", typeof(string));
    
            var machineIdParameter = machineId.HasValue ?
                new ObjectParameter("machineId", machineId) :
                new ObjectParameter("machineId", typeof(int));
    
            var invoice_NoParameter = invoice_No != null ?
                new ObjectParameter("invoice_No", invoice_No) :
                new ObjectParameter("invoice_No", typeof(string));
    
            var isLegacyParameter = isLegacy.HasValue ?
                new ObjectParameter("IsLegacy", isLegacy) :
                new ObjectParameter("IsLegacy", typeof(bool));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            var no_of_FreeDriesParameter = no_of_FreeDries.HasValue ?
                new ObjectParameter("no_of_FreeDries", no_of_FreeDries) :
                new ObjectParameter("no_of_FreeDries", typeof(int));
    
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("customerId", customerId) :
                new ObjectParameter("customerId", typeof(int));
    
            var subdiaryIdParameter = subdiaryId.HasValue ?
                new ObjectParameter("subdiaryId", subdiaryId) :
                new ObjectParameter("subdiaryId", typeof(int));
    
            var subAgentIdParameter = subAgentId.HasValue ?
                new ObjectParameter("subAgentId", subAgentId) :
                new ObjectParameter("subAgentId", typeof(int));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("locationId", locationId) :
                new ObjectParameter("locationId", typeof(int));
    
            var isMultiDeviceParameter = isMultiDevice.HasValue ?
                new ObjectParameter("IsMultiDevice", isMultiDevice) :
                new ObjectParameter("IsMultiDevice", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_LegacyMemberInsert_Result>("usp_LegacyMemberInsert", memberNameParameter, email_IDParameter, phone_NumberParameter, userIdParameter, reviveDeviceIdParameter, machineIdParameter, invoice_NoParameter, isLegacyParameter, startDateParameter, endDateParameter, no_of_FreeDriesParameter, customerIdParameter, subdiaryIdParameter, subAgentIdParameter, locationIdParameter, isMultiDeviceParameter);
        }
    
        public virtual ObjectResult<usp_AppMachineHistoryByMachineId_Result> usp_AppMachineHistoryByMachineId(string machine_Id_Val, Nullable<int> days)
        {
            var machine_Id_ValParameter = machine_Id_Val != null ?
                new ObjectParameter("Machine_Id_Val", machine_Id_Val) :
                new ObjectParameter("Machine_Id_Val", typeof(string));
    
            var daysParameter = days.HasValue ?
                new ObjectParameter("Days", days) :
                new ObjectParameter("Days", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AppMachineHistoryByMachineId_Result>("usp_AppMachineHistoryByMachineId", machine_Id_ValParameter, daysParameter);
        }
    
        public virtual ObjectResult<usp_AppMachineHistoryByProcessId_Result> usp_AppMachineHistoryByProcessId(string processId)
        {
            var processIdParameter = processId != null ?
                new ObjectParameter("ProcessId", processId) :
                new ObjectParameter("ProcessId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_AppMachineHistoryByProcessId_Result>("usp_AppMachineHistoryByProcessId", processIdParameter);
        }
    
        public virtual ObjectResult<usp_GetGroupLocationToBeShipByPriority_Result> usp_GetGroupLocationToBeShipByPriority()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetGroupLocationToBeShipByPriority_Result>("usp_GetGroupLocationToBeShipByPriority");
        }
    
        public virtual ObjectResult<usp_MachineActivityDetails_Result> usp_MachineActivityDetails(string dateFromstr, string dateTostr, Nullable<int> customerId, Nullable<int> subsidiaryId, Nullable<int> subAgentId, Nullable<int> locationId, Nullable<int> modeId)
        {
            var dateFromstrParameter = dateFromstr != null ?
                new ObjectParameter("DateFromstr", dateFromstr) :
                new ObjectParameter("DateFromstr", typeof(string));
    
            var dateTostrParameter = dateTostr != null ?
                new ObjectParameter("DateTostr", dateTostr) :
                new ObjectParameter("DateTostr", typeof(string));
    
            var customerIdParameter = customerId.HasValue ?
                new ObjectParameter("CustomerId", customerId) :
                new ObjectParameter("CustomerId", typeof(int));
    
            var subsidiaryIdParameter = subsidiaryId.HasValue ?
                new ObjectParameter("SubsidiaryId", subsidiaryId) :
                new ObjectParameter("SubsidiaryId", typeof(int));
    
            var subAgentIdParameter = subAgentId.HasValue ?
                new ObjectParameter("SubAgentId", subAgentId) :
                new ObjectParameter("SubAgentId", typeof(int));
    
            var locationIdParameter = locationId.HasValue ?
                new ObjectParameter("LocationId", locationId) :
                new ObjectParameter("LocationId", typeof(int));
    
            var modeIdParameter = modeId.HasValue ?
                new ObjectParameter("ModeId", modeId) :
                new ObjectParameter("ModeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_MachineActivityDetails_Result>("usp_MachineActivityDetails", dateFromstrParameter, dateTostrParameter, customerIdParameter, subsidiaryIdParameter, subAgentIdParameter, locationIdParameter, modeIdParameter);
        }
    }
}
