//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingConfiguration
    {
        public int Id { get; set; }
        public int ServiceTypeId { get; set; }
        public Nullable<decimal> InsuranceAmount { get; set; }
        public Nullable<int> PkgWt { get; set; }
        public Nullable<int> PkgLength { get; set; }
        public Nullable<int> PkgWidth { get; set; }
        public Nullable<int> PkgHeight { get; set; }
        public string MachineIdentifier { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
