//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Cities = new HashSet<City>();
        }
    
        public int StateId { get; set; }
        public string State1 { get; set; }
        public string state_code { get; set; }
        public Nullable<System.DateTime> aud_date { get; set; }
        public string aud_user { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
    }
}
