//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_users
    {
        public int Store_User_ID { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public string Full_Name { get; set; }
        public string Email_ID { get; set; }
        public string Phone { get; set; }
        public string Phone_Ext { get; set; }
        public string FaxCell_Phone { get; set; }
        public Nullable<int> Deactivate_Flag { get; set; }
        public string StoreNUmber { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    }
}
