//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubAgent
    {
        public SubAgent()
        {
            this.Customers_Locations = new HashSet<Customers_Locations>();
            this.JobOrder_header = new HashSet<JobOrder_header>();
        }
    
        public int SubAgent_ID { get; set; }
        public int Customer_ID { get; set; }
        public int Subsidiary_ID { get; set; }
        public string SubAgent_Ref_Code { get; set; }
        public int SubAgentTypeId { get; set; }
        public string SubAgentName { get; set; }
        public Nullable<System.Guid> AccountmanagerUserID { get; set; }
        public string Address { get; set; }
        public string CityName { get; set; }
        public Nullable<int> Primary_State { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Lease_Start_Date { get; set; }
        public Nullable<System.DateTime> Lease_end_date { get; set; }
        public string ContactName { get; set; }
        public string ContactAddress { get; set; }
        public string ContactCityName { get; set; }
        public Nullable<int> ContactState { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string ContactZipCode { get; set; }
        public bool Status { get; set; }
        public string ShipToAttention { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual ICollection<Customers_Locations> Customers_Locations { get; set; }
        public virtual ICollection<JobOrder_header> JobOrder_header { get; set; }
    }
}
