//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tablet_App_MemberActivity_Details
    {
        public int Membership_Activity_ID { get; set; }
        public Nullable<int> Machine_Activity_ID { get; set; }
        public string Membership_Id { get; set; }
        public Nullable<int> Devicemanufacturer_Id { get; set; }
        public Nullable<int> Howlongago_Id { get; set; }
        public Nullable<bool> pluggedinYes { get; set; }
        public string phonenumber { get; set; }
        public string Comments_reason { get; set; }
        public string Device_id { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string Invoice_No { get; set; }
        public Nullable<int> Location_id { get; set; }
    
        public virtual Membership Membership { get; set; }
        public virtual Tablet_App_Machine_Activity_Details Tablet_App_Machine_Activity_Details { get; set; }
    }
}
