//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPSSetting
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Psw { get; set; }
        public string ShipmentDescription { get; set; }
        public string ShipperNumber { get; set; }
        public string AccountNumber { get; set; }
        public string ShipperAddressLine { get; set; }
        public string ShipperCity { get; set; }
        public Nullable<int> ShipperPostalCode { get; set; }
        public string ShipperStateProvinceCode { get; set; }
        public string ShipperCountryCode { get; set; }
        public string ShipperName { get; set; }
        public string ShipperAttentionName { get; set; }
        public string ShipperPhone { get; set; }
        public string ShipFromAddressLine { get; set; }
        public string ShipFromCity { get; set; }
        public Nullable<int> ShipFromPostalCode { get; set; }
        public string ShipFromStateProvinceCode { get; set; }
        public string ShipFromCountryCode { get; set; }
        public string ShipFromAttentionName { get; set; }
        public string ShipFromName { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public string ShipmentChargeType { get; set; }
        public string ServiceCode { get; set; }
    }
}
