//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public UserType()
        {
            this.FAQ_Management = new HashSet<FAQ_Management>();
            this.MapMode_UserType = new HashSet<MapMode_UserType>();
            this.User_Level = new HashSet<User_Level>();
        }
    
        public int Id { get; set; }
        public string UserType1 { get; set; }
        public Nullable<System.DateTime> Aud_Date { get; set; }
        public string Aud_User { get; set; }
    
        public virtual ICollection<FAQ_Management> FAQ_Management { get; set; }
        public virtual ICollection<MapMode_UserType> MapMode_UserType { get; set; }
        public virtual ICollection<User_Level> User_Level { get; set; }
    }
}
