//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Level
    {
        public User_Level()
        {
            this.UserMap_Controller_Action = new HashSet<UserMap_Controller_Action>();
            this.User_Level_Menu_Mapping = new HashSet<User_Level_Menu_Mapping>();
            this.Users = new HashSet<User>();
        }
    
        public int User_Level_ID { get; set; }
        public string User_Level_Name { get; set; }
        public string User_Level_Description { get; set; }
        public Nullable<int> UserTypeId { get; set; }
        public string Page_Access_Code { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
    
        public virtual ICollection<UserMap_Controller_Action> UserMap_Controller_Action { get; set; }
        public virtual ICollection<User_Level_Menu_Mapping> User_Level_Menu_Mapping { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
