//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid User_ID { get; set; }
        public int User_Level_ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email_ID { get; set; }
        public string Office_Phone { get; set; }
        public string Office_phone_etx { get; set; }
        public string Cell_Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<int> Subsidiary_ID { get; set; }
        public Nullable<int> SubAgent_ID { get; set; }
        public Nullable<int> Location_ID { get; set; }
        public Nullable<int> Deactivate_Flag { get; set; }
        public Nullable<System.Guid> Created_by { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.Guid> Modified_by { get; set; }
        public Nullable<System.DateTime> Modified_Date { get; set; }
        public bool status { get; set; }
        public bool IsLockedOut { get; set; }
        public Nullable<System.DateTime> LastPasswordChangeDate { get; set; }
        public Nullable<System.DateTime> LastLoginActivity { get; set; }
        public Nullable<int> Manufacturer_Id { get; set; }
        public Nullable<bool> IsUserLogging { get; set; }
        public Nullable<int> LoggingTypeID { get; set; }
    
        public virtual User_Level User_Level { get; set; }
    }
}
