//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Revive.Redux.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReviveMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReviveMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Revive.Redux.UI.ReviveMessages", typeof(ReviveMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to activate this user?.
        /// </summary>
        public static string ActivateInfo {
            get {
                return ResourceManager.GetString("ActivateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Successfully..
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully..
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated Successfully..
        /// </summary>
        public static string Deactivate {
            get {
                return ResourceManager.GetString("Deactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to deactivate this user?.
        /// </summary>
        public static string DeactivateInfo {
            get {
                return ResourceManager.GetString("DeactivateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully..
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully..
        /// </summary>
        public static string MachineSpecSaveInfo {
            get {
                return ResourceManager.GetString("MachineSpecSaveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully..
        /// </summary>
        public static string MachineSpecUpdateInfo {
            get {
                return ResourceManager.GetString("MachineSpecUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information has been saved successfully..
        /// </summary>
        public static string ManageUserSaveInfo {
            get {
                return ResourceManager.GetString("ManageUserSaveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information has been Updated successfully..
        /// </summary>
        public static string ManageUserUpdateInfo {
            get {
                return ResourceManager.GetString("ManageUserUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order successfully Removed.
        /// </summary>
        public static string OrderRemove {
            get {
                return ResourceManager.GetString("OrderRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software version has been added successfully..
        /// </summary>
        public static string SoftwareVersionSaveInfo {
            get {
                return ResourceManager.GetString("SoftwareVersionSaveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software version has been Updated successfully..
        /// </summary>
        public static string SoftwareVersionUpdateInfo {
            get {
                return ResourceManager.GetString("SoftwareVersionUpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully..
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
